### ISSUE TITLE
Generating town settings

### ISSUE THREAD

**Issue by michellekarunaratne** [covid19-model/simulator#12] opened 2020-10-04 15:18 UTC
hi,

There is an overflow issue when downscaling the population_per_age_group array which gives minus values to some of the age group. You might have to change the data type into int64 in town_settings_[town_name].py file.

**Comment by larslorch** [comment] 2020-10-05 06:47
Hi, thanks for your comment. Can you be a bit more specific at what point in the code, which variable, and under what settings the error occurs? 
Thanks a lot!

**Comment by michellekarunaratne** [comment] 2020-10-05 11:55
I tried to recreate the "Tubingen_settings_10.pk" file for that used the "lib/settings/town_settings_tubingen.py" file. When allocating nodes to age groups using the downscaled values of the in the population_per_age_group list array in line 18 in the sim/lib/settings/town_settings_tubingen.py file, the conversion from actual values to downscale value gives minus values for some list elements. 

I added the following dtype, then the downscaling values were accurate as well.
population_per_age_group = np.array([
    13416,  # 0-4
    18324,  # 5-14
    67389,  # 15-34
    75011,  # 35-59
    41441,  # 60-79
    11750],dtype='int64') # 80+ 

Having minus values gave me an error in line 155 (file: sim/lib/town_data.py ) saying 

people_age+=list(np.random.multinomial(n=1, pvals=age_proportions, size=pop).argmax(axis=1))

pval should not have minus values etc. After adding dtype='int64' the error was resolved.

**Comment by larslorch** [comment] 2020-10-05 13:42
Okay, what was your downscaling factor for `population_per_age_group`?

**Comment by michellekarunaratne** [comment] 2020-10-05 13:50
Hi,
I didn't change any value in the "town-generator.ipynb" file I just wanted to see whether I can recreate exact same setting file " Tubingen_settings_10.pk " by keeping the down sampling value = 10 which was mentioned in the "town-generator.ipynb" file.

**Comment by larslorch** [comment] 2020-10-05 14:08
When downloading the master branch, I cannot reproduce your error when running town-generator.ipynb.
Do you have all requirements as specified in `requirements.txt`? Does your error indicate negative values for `age_proportions` or do they not sum up to 1?

**Comment by michellekarunaratne** [comment] 2020-10-06 12:48
Hi,
I have added all the requirements mentioned in the requirement.txt.

yes, since the population_per_age_group variable gets downsized by 10 after the conversion , some of the values contains (-) values.

**Comment by larslorch** [comment] 2020-10-06 13:03
At the moment I'm still unable to reproduce this, but we are working on finding the reason for your issue.
Could you describe precisely what steps you execute to obtain the error, after having downloaded `master` freshly from the repository? Simply running `town-generator.ipynb` top-to-bottom works fine for me.

**Comment by mindika** [comment] 2020-10-07 02:33
Hi, it seems to be a datatype issue (recreated as below on my windows PC). Thanks!
![image](https://user-images.githubusercontent.com/4626061/95280783-863f8a00-08a1-11eb-9a56-d8653debd1b2.png)

**Comment by larslorch** [comment] 2020-10-07 09:45
I just pushed a fix to `master`, please let us know if you encounter any further issues. 
I believe the issue arose from your machine having `np.int16` as default. Many thanks for helping us improve the code!

**Closed as completed by larslorch** 2020-10-07 09:45 UTC
